language: node_js
node_js:
- '6'
sudo: false
cache:
  directories:
  - node_modules
before_install:
- npm config set spin false
- npm install -g bower
- npm install phantomjs-prebuilt
install:
- npm install
- bower install
script:
- npm test
env:
- CXX=g++-4.8
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-4.8
deploy:
  provider: heroku
  api_key:
    secure: LlEJieTGfZtDHp+W9003nZWZf62jVFpRARZb1pvuw9loO34Y3qWLyDTyHUGmR22z0W720Hk5dUDytPxxZmuKmoy33gZX9GEiRiLM51RbIcqogtZfNlWMf2q3LIhdzq3IhC0TLyqaYNdIyUGyNHYa6GkzxoqCO+afS3UZgwZMwl7UzNDdZi6mqgAncdq+bv3UhQVgJ/sjjMV9MZDTa7m1QQTGkSx3e1rWx6x96xsATgaq+UA1B8vh/os9ToaoTH/ZxmwEnL9GJ6N4zyj/d3DlBJp4OPmfgak25mKtgSpKBXXGoF4u08VwUtaUPu/E36snIoY5nwzx+xtWa0WD2JeQkg9lzOB3PIsHfKLwjUhvHokhv6D7g9b3lfTUitL2E9usNpm+H8jBCX8raDDJg+B/I8rJ8x4eu162Te/4kURwRhihf7NtpY22IoqFd0gfVArXCN1WYePaYMANvauR4IBzhy+VHecDYDxvjSyg/pyX3/cvKcOtyxn0Sv8QnugU5IQ9bOC6zDZ3+fCmNFDKgU187UvEd+Vm5p3YgsARKsnwXrOVc/XNy8UJA9dIc3/HLhW65ndjv/TusQodaaE2ltnoEqTxZEG1GASQgXZD7kRdJ2QMGYC8IBkrhJQdv9WFkyGMblgfC47gUqBxOl8IKbklO0Jp3dgeDFRynWIIzcL6YD4=
  app: nameless-sierra-51258
  on:
    repo: damianhouse/peepchatui
